name: whatsapp-clone
version: '3'

services:

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000/tcp
    entrypoint: /surreal start --auth --user root --pass password --allow-funcs

  surrealdb-migrate:
    container_name: surrealdb-migrate
    build:
      context: .
      dockerfile: ./dockerfiles/surrealdb-migrate.dockerfile
    volumes:
      - ./schema.surql:/migrations/schema.surql:ro
    environment:
      - ENDPOINT=http://surrealdb:8000
    restart: on-failure
    depends_on:
      - surrealdb

  ## Microservices

  authentication-microservice:
    container_name: authentication-microservice
    build:
      context: .
      dockerfile: ./backend/microservices/authentication/Dockerfile
    env_file:
      - ./backend/microservices/authentication/.env.dev
    environment:
      - SURREALDB_URL=surrealdb:8000
    ports: [ 4001:4000 ]
    restart: on-failure
    depends_on:
      - surrealdb-migrate

  profile-microservice:
    container_name: profile-microservice
    build:
      context: .
      dockerfile: ./backend/microservices/profile/Dockerfile
    env_file:
      - ./backend/microservices/profile/.env.dev
    environment:
      - SURREALDB_URL=surrealdb:8000
    ports: [ 4002:4000 ]
    restart: on-failure
    depends_on:
      - surrealdb-migrate