name: whatsapp-clone
version: '3'

services:

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    ports:
      - 8080:8080/tcp
    entrypoint: /surreal start --auth --user root --pass password --allow-funcs

  surrealdb-migrate:
    container_name: surrealdb-migrate
    build:
      context: .
      dockerfile: ./dockerfiles/surrealdb-migrate.dockerfile
    volumes:
      - ./schema.surql:/migrations/schema.surql:ro
    environment:
      - ENDPOINT=http://surrealdb:8000
    restart: on-failure
    depends_on:
      - surrealdb