name: whatsapp-clone
version: '3'

services:

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000/tcp
    entrypoint: /surreal start

  surrealdb-migrate:
    container_name: surrealdb-migrate
    build:
      context: .
      dockerfile: ./dockerfiles/surrealdb-migrate.dockerfile
    volumes:
      - ./schema.surql:/migrations.surql:ro
    environment:
      - ENDPOINT=http://surrealdb:8000
    restart: on-failure
    depends_on:
      - surrealdb

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.dev-config.yaml:/etc/prometheus/prometheus.yml:ro

  autometrics:
    container_name: autometrics
    image: autometrics/am-proxy
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    ports:
      - 6789:6789

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 4317:4317   ## gRPC endpoint
      - 16686:16686 ## UI dashboard endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  ## Microservices

  authentication-microservice:
    container_name: authentication-microservice
    build:
      context: .
      dockerfile: ./backend/microservices/authentication/Dockerfile
    env_file:
      - ./backend/microservices/authentication/.env.dev
    ports: [ 4001:4000 ]
    restart: on-failure
    depends_on:
      - surrealdb-migrate

  profile-microservice:
    container_name: profile-microservice
    build:
      context: .
      dockerfile: ./backend/microservices/profile/Dockerfile
    env_file:
      - ./backend/microservices/profile/.env.dev
    ports: [ 4002:4000 ]
    restart: on-failure
    depends_on:
      - surrealdb-migrate