scrape_configs:

  - job_name: authentication-microservice
    metrics_path: /metrics
    static_configs:
      - targets: [ authentication-microservice:5000 ]
    scrape_interval: 10s

  - job_name: profile-microservice
    metrics_path: /metrics
    static_configs:
      - targets: [ profile-microservice:5000 ]
    scrape_interval: 10s