---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgA9FAKK2OKqSbgBVCtLtsmI7S2UcLz+E+yMr8BIxVC7VcU1pf1JGwMpku+aFyqkt6OVzuEGf5EU1L3p0Qbk2Xpd2JT1b5M7Jd5B8YR1srQPNLEeJvrSDJkpVNkPk7ZvuGbfYOKZu4D+va/bPMQdzNWvXbSdLgNCZXxhp/6YAaBU/8bN9o9ml18+paiZJyb/ufN+64xIKV8MjO82cLymgdKyIM42n1gfLmEJV13kan+TsZRSJ+hU0/ZGThmCIhP/+hMNaoRatuxfER+hGhys71zx4y9hr05Itc9b4UoZl+pjlGJWpcs/iWt9powo0BPUKRFdhoF4lNfU3ki/sv+HvbGoRlylOe0VonAVS7JVdgq+JkauG00UAvdiql8v/K0NdihRwAZZIf4ch11nPiLe2pJfkaojUpOj741MBrzKPuVwqT9GuT+/PH+77HkoOAQiEr1gHhPoLmHcGsqERwWnaaKrgyEiA31innDnUUbwT0tezS16AbueonG0U6TPofVZE6NLr0XIV9qAOgqexbIOkfOltUhQXpp1KGR9f5WG4LBM4K5eR981f2LMnIxaFX8oiGZviqisJgtftnfbm9p/aCY2+nkas+j5AEUr4+2SlSDW+7RB+tZeqFStW/MnC1rpp8L0T6umJRHIMZQ2SsZkjopNooUZLiGXXvKZmBYKub8mIdafSbRvSbgOdDReljXxQ9Ma2UYouJQLUXf5wbWCJPQU8Xc+qs/7MgxK9mwV3gS87YvZhIp/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cert-manager
