---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCp8HlII2Gyuji38+weFk6m39FWql8bHKM1Cp7J36u4SHTWKXwTS5aiJHB09qLXA87ag+MNZ5E/8JmnS4ghzJmkchBGIFjGduoqDuynAkPQ+bh4LmzE0RYruTIoQlMjSHIjn1+0JMVQ4cWx5sDe3eh7OngAw3JaOcscpWwgo9quccu+UaMawh9qCyomw0rY49cH1l4rAH8E24QUIDojUA/cv6ERt/1pSQab35XdD4t6h8stvFVM43WHIn4LpjxgBi943TWCyCloxjnRVaH7Ef9s5t0t3eySHlapAMCgszHmH5zvhHIUhRSP0KkKT5TxVIwrASFrAFifaNz9RMuZx0+SZYXLcCYps4jH6WPWG+mpiX/Jb2m192NpWmQ+PuILn92w6stlnxSaRid72SoqDj4MhnPOCi305a34J4l8VmDB6ZrQzqxweQF+D884xOU+p+mVf2jpItp7SHdMb2Uo/RsxENglInBOqUpXRN43wSnQiForA0N3clpLV07WogvsGYNIxGORjrxI13SbRPVU2enyO+9cOtmdfW/5ENI8JW5wKVah2fnHkJMex2WpdnTSb93NodqjrZnE7q0mIJf2/zvMzoxcB871/UxbCAFpeShuVT6EKrrZPDPR6rYQzL2mEpa/cnBR5CmE4qn6rWreejVdBD9soZK8h8CxUtDC1ksBwGn3OpCOt5EhH+087SD5i6T/io91BRE0zdwg6+QFV/3kXisGYYdMs+/13HUntGX/RQ/mzKPb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cert-manager
