## CertManager adds certificates and certificate issuers as resource types in Kubernetes clusters,
## and simplifies the process of obtaining, renewing and using those certificates. It can issue
## certificates from a variety of supported sources, including Let's Encrypt, HashiCorp Vault etc.
## It will ensure certificates are valid and up to date, and attempt to renew certificates at a
## configured time before expiry.

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cert-manager-helm-installation
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.13.1
    helm:
      releaseName: cert-manager
      valuesObject: { }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: v1
kind: Namespace

metadata:
  name: cert-manager