prometheus:
  prometheusSpec:

    ## If true, a nil or {} value for prometheus.prometheusSpec.podMonitorSelector will cause the
    ## prometheus resource to be created with selectors based on values in the helm deployment,
    ## which will also match the podmonitors created.
    podMonitorSelectorNilUsesHelmValues: false

    ## If true, a nil or {} value for prometheus.prometheusSpec.serviceMonitorSelector will cause
    ## the prometheus resource to be created with selectors based on values in the helm deployment,
    ## which will also match the servicemonitors created.
    serviceMonitorSelectorNilUsesHelmValues: false