apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: gateway-api
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/Archisman-Mridha/whatsapp-clone
    targetRevision: HEAD
    path: kubernetes/yaml/argo/cd/apps/gateway-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true