apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: roles
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/Archisman-Mridha/whatsapp-clone
    targetRevision: HEAD
    path: kubernetes/roles
    directory:
      recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true