apiVersion: whatsappclone.io/v1alpha1
kind: Application
metadata:
  name: authentication-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/whatsapp-clone-authentication-microservice:latest
  replicas:
    min: 1
    max: 3
  secretName: authentication-microservice
  port: 4000