apiVersion: whatsappclone.io/v1alpha1
kind: Application
metadata:
  name: authentication-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/whatsapp-clone-authentication-microservice:4ee1e52cfd722b83b12dd6f9562cb538dabe3228
  replicas:
    min: 1
    max: 3
  secretName: authentication-microservice
  port: 4000