apiVersion: whatsappclone.io/v1alpha1
kind: Application
metadata:
  name: authentication-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/whatsapp-clone-authentication-microservice:92d7378f11a03b314a49fb2f85236b9b2eca403d
  replicas:
    min: 1
    max: 3
  secretName: authentication-microservice
  port: 4000