apiVersion: whatsappclone.io/v1alpha1
kind: Application
metadata:
  name: profile-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/whatsapp-clone-profile-microservice:4937890d86910f50b43866d6a2421332e2b26205
  replicas:
    min: 1
    max: 3
  secretName: profile-microservice
  port: 4000