apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: opa-gatekeeper
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system

  source:
    repoURL: https://github.com/Archisman-Mridha/whatsapp-clone
    targetRevision: HEAD
    path: kubernetes/base/opa-gatekeeper

  syncPolicy:
    automated:
      prune: true
      selfHeal: true