apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: surrealdb-migrate
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: surrealdb

  source:
    repoURL: https://github.com/Archisman-Mridha/whatsapp-clone
    targetRevision: HEAD
    path: kubernetes/base/surrealdb-migrate

  syncPolicy:
    automated:
      prune: true
      selfHeal: true