apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: main
  namespace: cockroachdb

spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Mi
        volumeMode: Filesystem
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 1Gi

  tlsEnabled: true

  image:
    name: cockroachdb/cockroach:v23.1.11

  # Nodes refers to the number of crdb pods that are created via the Statefulset.
  nodes: 3