apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: emissary-ingress
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: emissary-system

  source:
    repoURL: https://app.getambassador.io
    chart: emissary-ingress
    targetRevision: 8.8.2
    helm:
      releaseName: emissary-ingress
      valuesObject: { }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true