apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 52.0.0
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:

        prometheus:
          prometheusSpec:

            ## If true, a nil or {} value for prometheus.prometheusSpec.podMonitorSelector will cause the
            ## prometheus resource to be created with selectors based on values in the helm deployment,
            ## which will also match the podmonitors created.
            podMonitorSelectorNilUsesHelmValues: false

            ## If true, a nil or {} value for prometheus.prometheusSpec.serviceMonitorSelector will cause
            ## the prometheus resource to be created with selectors based on values in the helm deployment,
            ## which will also match the servicemonitors created.
            serviceMonitorSelectorNilUsesHelmValues: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: v1
kind: Namespace

metadata:
  name: prometheus