apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: surrealdb
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: surrealdb

  source:
    repoURL: https://github.com/Archisman-Mridha/whatsapp-clone
    targetRevision: HEAD
    path: kubernetes/workspaces/production/surrealdb
    plugin:
      name: kustomize-enable-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true