---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-dns-config
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgDKN1snljSrY5uUEyeFXHZpi9RJUm8Uf7FQb+a2Eak8e3kVNHZ0qEWXJuZmfKhkE8THYg2bwAyJ5rQf1RPE4rtbnbaqY3A58bJUs3c2dON3feY00OzPJaG7yO2dDlShJD66AG6o/wa07GwXYvT1U684xAom/8PFKWLAbPG29UTy/lg8+3fvEPwnsLngCdjLNuhZw0TkOMfia8lqi3Ks4Dvlh8SUQ2H3KD9xC9s9mk+mFeLOucbYkmvYdIEZf5mHtn7W+jxhAsyglmCu9OsHR1ZfFPz0ZgW5tpJGBcFdczFKj3Fo1QVdyD7bf/I6tIT7CeFb4lSfVzvtjJkIHiEvTFt4/jrvZAKo9gH7+IUFuLLQHsUIRuKSuQzqg/CnT1DtGeF/1oWJzKIFupRZC5je3YTx2YvCsLLYhdnzZnyfKoJNhM9tOWxXZBb7WSZaXzNv2cnswm3JEh0YaC6oUjA3G7+xX9J/S1CyY2FAkINthM5vlsUPVsCCR4Q2hqJHukNQ8tE9GXXdInRQkg4zjJbAYOFaBZZBlbgdgFN9lp2mI4zoAEzzqPOHxhco6PrRS7hfUoa4No6a1Fcj7RhcgiIcJGjRpuPrWFL0SFX9aWTEKPXszpezW4s1wEpe+mWQ8dbNtpgopQskE7hoZQfwOVusMVtKlRu05TWXBHt4e0sFpf/zvQ0ECsxcuESwLK+yOOcC+G0OyyXblQW3K5CB+9qbel4DfjrWiYQVrinkpJjGWh8=
    CF_API_KEY: AgAnYN5I3uIwVIQO6vu+ZORW3lYfAY1lBVtA8f97cRVavzJrAsnGcgc8itIDR/PY3XcmkU1+dvP9mbxB0/VJ5XsZju0Eqctx6bctMryqJVHRpeGTgzLr7VfY5cvLT+k7Am95ZSjsAnyCZnMr2cO6lLj8CSA4Ycz1E6zlFqHz7bULwn4StV6kKfw90q2cH93VExpdamhybwKhBxpJdEo+yJHxvz0O9C/fNCCSeY6crKCgBYnmmoolYM/AjNvi8/G3+awlu2Q/lt/ARgv9g2MtrGCbQ71GbWMU/A4iElOYgLXrmHdJD8hltpQYuzL+K3rjqXGd3qoFKR9muwTw/rb2pHTnRvHvZlpkw5wZSx+0itZ0ZKxrhOiogPAoAxKsoXHOK6Vau1pie3/6WPVbDQEo053FZXbfnHma36oyf1sSduFP82uhwqp2l565j4pISmNSQhnY1zCuBGfmNhfur9ln6Dgrw5Nw6rVUKWgZSY8wzcvWMBhJMAJ4Ibm47I4Zt4jIwSg+tUMj4KqVashgqJz3EIxMYmuWFsf1czF/ErZaujdQEP2SaNdPpgK3PMvB8XBokrihv3ISAQ2Igtb0icPs5YXRYPoL6sfbvLPdLSmpOMHvSr+ytYE72We99puUL0SJUbVYz/NYoGND8sRCCuZxECSYSTVbni366VWzHdK+2N0rw1gfFZ43Uek4iPwJ7AouV3rBHztPdwifpVEgQVn8BVs+jFQSs7MaprVLCHxcDW5ukWcRx2ht
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-dns-config
      namespace: external-dns
