---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-dns-config
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgCJUoS97DSTg3OO2dz9OCeyn0NH98rAXQFzc0nyqTTMN1/nMzD1yqBjI6ivthaqsqw2G90v/M0bQ8I4J5J540mBgPGT6YtfneGhOpuzSaPg7ZuGr4hHzUneWrwHqbDfU+57I4Gt+s9WXoLxfK3W9sWOQZ3tMVYvSV730zzM9lAhF8KV6aktqdf492Topdxuq8dBZJ7XBjJ4h7nXyqWtFOjq9EYu9zRbAq2VTlgwkBx+ZyZSaFwaZqWs2Z7Ks7YOf7CZqCFMdX5KZqtjzl0No27UykhkTFEpFuhYHpKGLNOFYKSljIQcArctY8JWnrNXihFSd/PfGH+vNsyb1sCiF6xSSySwtI1/FvmzNTy4oe8BqcEHoXspdigWP9sQJQdBvoFNe60FFu5tWVdK6vj+A2oDcVfFLZRj5UEnW5BIqD5iN/GcBJhiZfIOm92b11Hu1WnmgnA9G7wWXHMF4GFIG8svaMIlOxlOT4s7ll05zFCjF4s4EjJtSW/+RJnYodtZb9u3ochZeURgrmVoeBgx3LyxrCCuM2WxbrqPgvhV6m+/wvnQRJnHfSgW1gUhCKSVQTYeZwYS3JiQdvOK+lzR2GWbW3ip7WtUgs2VyrKMP0YsnPTC5Cqlf5vtzRovoKAsqbtmLQkzR7A1tBGEkoACt58QdTzI6YXpVOD1+3MFy5lsTM4cC08h7rgI+bEA+uULiZz6eC4iCufVxoMwhiHr5RJdlOXylApknNuUA/157PI=
    CF_API_KEY: AgATMj+qzGxgUtA3P2Jc0Ugk+ewkbS79G0iFoiGbk/CrNByg73+5Kp0cdjkZV2SLyZYI1HvXnRri7fcMe4HDz7zs0O9v9YkndLazanvgaFMbErxgifKAyiIrgv4JcNa2ERobS3AlkgNmjM+YS/ykero+6i4DHW9Q7cK6iTqCVlqiYvMMslUzijLEQf6qtrholaS0vM3Pr1sknopced0beVvbLlXgqWUFVb0mNAwOloSYClpQHibmPz2x/9ZJaBjZse5z/g7yTknL+s/jnLgJV/2W/CwGuyNfFfkGXoI4/BpIEy5STPywb7lTGjpzyB/7QrFrKRnoFJ6Rh+xk6R6Cwllbk8kdpu43FxUEUBdO/gKB7kAw3KNEUJQfVC2VKl3vQQ2s0xeOgocaMEedFpEQGNgPBx8WtwPJWwsr/WkdjwqRvNI7FBjd/Kz2rj8GBN5dQeMQQjzSUnu0wLqgrlxmo60BZhBhWVqRuTP1NDe1EGuzoYuXj1RciUfHcuTmmVd+vLHBskCb1sRzXocsYmn/zKo7GymGHPonIwkf8r0HNepwOt8eCxAQgvuhODGqFyF2zxfF0Ct309xExFixQXS7/0qByOmkCK+npJCDj8QmSVn/k27cPQh+4m0QJYDfbntC3JcBZ65fdVciVmvb5RHPBy60ebmOQMcYbdWhwTfvryHna1V4o76kVIdK7Z34L493aSMnKB6aM8y6h8Sz9YuAZIYmPAy9hqcUJNVu52pOYXERNSIdKZ+V
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-dns-config
      namespace: external-dns
