apiVersion: whatsappclone.io/v1alpha1
kind: Application
metadata:
  name: authentication-microservice
  namespace: microservices

spec:
  image: archismanmridha/whatsapp-clone-authentication-microservice:0.0.1-alpha
  replicas:
    min: 2
    max: 3
  resources:
    cpu: 100m
    memory: 100Mi
  secretName: authentication-microservice
  port: 4000
